//기본적인 웹 페이지 골격 구성
import { Control } from "./Control";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by bidanee",
};

export default async function RootLayout({ children }) {
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL + "topics", {
    cache: "no-store",
  }); // 성능 저하...
  const topics = await res.json();

  return (
    <html>
      <body>
        <h1>
          <a href="/">WEB</a>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
